services:
  hatchery:
    build:
      context: .
    command: node .output/server/index.mjs
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal
      - dragcave

  db:
    image: mariadb:10
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    networks:
      - internal

volumes:
  dbdata:

networks:
  internal:
  dragcave:
    external: true
