services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: npm run dev
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mariadb:10
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - internal

volumes:
  dbdata:
  node_modules:

networks:
  internal:
